---
title: "The Residuals Exploratory Data Analysis"
subtitle: "Data Collected from The Islands Virtual Population"
author: 
  - Bhagatinder Longia
  - Musab Muhammad
  - Muntasir Munem 
  - Shea Munson 
  - Chloe Syriac
date: today
date-format: long
header-includes:
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{pgfplots}
format: pdf
---

```{r}
#| echo: false
#| eval: true
#| warning: false
#| message: false
# Loading Data
library(tidyverse)
library(patchwork)
data <- read.csv("cleaned_data.csv")
attach(data)
```

# Summary Statistics

# Checking Assumptions

# Plots

Here we have boxplots for the scores by both treatment and age.
```{r, fig.width = 10, fig.height = 5}
#| echo: false
#| eval: true
#| warning: false
#| message: false
# By Treatment
tr <- ggplot(data, aes(x=treatment, y=score, fill = treatment)) + 
  geom_boxplot() +
  scale_x_discrete(labels = c("Coffee", "Coffee (Decaf)", "Energy Drink", 
                              "Energy Drink (Decaf)", "Water")) +
  scale_fill_brewer(palette = "Set1") + 
  labs(title = "Problem Solving (20 min) Score Categorized by Drink", 
       x="Treatment (Drink Type)", y="Problem Solving (20 min) Score") +
  theme(legend.position = "none")
  
# By Age
ag <- ggplot(data, aes(x=age_group, y=score, fill = age_group)) + 
  geom_boxplot() +
  scale_fill_brewer(palette = "Set2") + 
  scale_x_discrete(labels = c("36-54", "55+", "18-35")) + 
  labs(title = "Problem Solving (20 min) Score Categorized by Age Group", 
       x="Age Group", y="Problem Solving (20 min) Score") +
  theme(legend.position = "none")

(tr + ag) + plot_layout(widths = c(1,1))
```

